### ISSUE TITLE
Still cannot communicate with inbox service though the steps for GMail already done.

### ISSUE THREAD

**Issue by knedyz** [steam-account-creator/Steam-Account-Generator#100]
Stated above, though I've already finished the steps, it still doesn't work. https://media.discordapp.net/attachments/487689767635386368/756212337538629673/unknown.png?width=1179&height=618

**Comment by knedyz** [comment]
fixed it somehow

**Comment by VacCatGT** [comment]
omg men pls help discord???? VacCat#7795

**Comment by Melanite** [comment]
> omg men pls help discord???? VacCat#7795

try unchecking random email
