### ISSUE TITLE
New feature: Join a steam group by url/id

### ISSUE THREAD

**Issue by lev4ukpavel2** [steam-account-creator/Steam-Account-Generator#14]
It would be cool if there was a feature so created account would join a steam group you specify.

**Comment by xsilent007** [comment]
Here's how to do it using xNet request (from my old generator)
`using (var JoinReq = new Request())
{
    JoinReq
        .AddParam("action", "join")
        .AddParam("sessionID", Cookies["sessionid"]);
    JoinReq.SetCookies(Cookies);

    JoinReq.Post("https://steamcommunity.com/groups/" + Params.GroupUrl);
}`

**Comment by EarsKilla** [comment]
After ~half year it was implemented 🤣 
![image](https://user-images.githubusercontent.com/17800772/65836990-a1290700-e2fb-11e9-977c-225ae88dc455.png)

Most code is rewritten and at this moment for example, it's don't save accounts to file.  
If all gonna fine i will done and push all changes in few days in `dev` branch...
