### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by caiovrcombat** [steam-account-creator/Steam-Account-Generator#28]
Print: http://prntscr.com/ofc4dg

Language: Português-Brazil

Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
```
System.Runtime.Serialization.SerializationException: O tipo 'System.Linq.Enumerable+AppendPrepend1Iterator`1[[SteamAccCreator.Models.GameInfo, SteamAccCreator, Version=1.1.3.3, Culture=neutral, PublicKeyToken=null]]' no assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' não está marcado como serializável.
   em System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   em System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _)
   em System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   em System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   em System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   em System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   em System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   em System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   em System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   em SteamAccCreator.Utility.DeepClone[T](T obj)
   em SteamAccCreator.Models.Configuration.Clone()
   em SteamAccCreator.Gui.MainForm.<BtnCreateAccount_Click>d__12.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

************** Assemblies Carregados **************
```
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3815.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SteamAccCreator
    Versão do Assembly: 1.1.3.3
    Versão do Win32: 1.1.3.3
    Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/SteamAccCreator.exe
----------------------------------------
NLog
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.5.11.8645
    Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/NLog.DLL
----------------------------------------
Geckofx-Core
    Versão do Assembly: 60.0.26.0
    Versão do Win32: 60.0.26.0
    Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/Geckofx-Core.DLL
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3801.0 built by: NET48REL1LAST_B
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3815.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3815.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
mscorlib.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Configuration
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3825.0 built by: NET48REL1LAST_B
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3825.0 built by: NET48REL1LAST_B
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
RestSharp
    Versão do Assembly: 106.5.4.0
    Versão do Win32: 106.5.4.0
    Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/RestSharp.DLL
----------------------------------------
Newtonsoft.Json
    Versão do Assembly: 12.0.0.0
    Versão do Win32: 12.0.1.22727
    Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Geckofx-Winforms
    Versão do Assembly: 60.0.26.0
    Versão do Win32: 60.0.26.0
    Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/Geckofx-Winforms.DLL
----------------------------------------
```
************** Depuração JIT **************
Para habilitar a depuração just-in-time (JIT), o arquivo .config deste
aplicativo ou computador (machine.config) deve ter o valor
jitDebugging definido na seção system.windows.forms.
O aplicativo também deve ser compilado com a depuração
habilitada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando a depuração JIT está habilitada, qualquer exceção sem tratamento
será enviada ao depurador JIT registrado no computador,
em vez de ser tratada nesta caixa de diálogo.

**Comment by despa1r1337** [comment]
> Print: http://prntscr.com/ofc4dg
> 
> Language: Português-Brazil
> 
> Consulte o final desta mensagem para obter detalhes sobre como chamar a
> depuração just-in-time (JIT) em vez desta caixa de diálogo.
> 
> ************** Texto de Exceção **************
> System.Runtime.Serialization.SerializationException: O tipo 'System.Linq.Enumerable+AppendPrepend1Iterator`1[[SteamAccCreator.Models.GameInfo, SteamAccCreator, Version=1.1.3.3, Culture=neutral, PublicKeyToken=null]]' no assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' não está marcado como serializável. em System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type) em System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _) em System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
> em System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
> em System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
> em System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
> em System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
> em System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
> em System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
> em SteamAccCreator.Utility.DeepClone[T](T obj)
> em SteamAccCreator.Models.Configuration.Clone()
> em SteamAccCreator.Gui.MainForm.<BtnCreateAccount_Click>d__12.MoveNext()
> --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
> em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_0(Object state)
> 
> ## ************** Assemblies Carregados **************
> mscorlib
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3815.0 built by: NET48REL1LAST_C
> Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ## SteamAccCreator
> Versão do Assembly: 1.1.3.3
> Versão do Win32: 1.1.3.3
> Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/SteamAccCreator.exe
> ## NLog
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.5.11.8645
> Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/NLog.DLL
> ## Geckofx-Core
> Versão do Assembly: 60.0.26.0
> Versão do Win32: 60.0.26.0
> Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/Geckofx-Core.DLL
> ## System
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3801.0 built by: NET48REL1LAST_B
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ## System.Windows.Forms
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3815.0 built by: NET48REL1LAST_C
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ## System.Drawing
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ## System.Core
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3815.0 built by: NET48REL1LAST_C
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ## mscorlib.resources
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
> ## System.Configuration
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ## System.Xml
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## System.Data
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ## System.ServiceModel
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3825.0 built by: NET48REL1LAST_B
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
> ## System.Runtime.Serialization
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3825.0 built by: NET48REL1LAST_B
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ## RestSharp
> Versão do Assembly: 106.5.4.0
> Versão do Win32: 106.5.4.0
> Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/RestSharp.DLL
> ## Newtonsoft.Json
> Versão do Assembly: 12.0.0.0
> Versão do Win32: 12.0.1.22727
> Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/Newtonsoft.Json.DLL
> ## System.Numerics
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ## System.Windows.Forms.resources
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
> ## Accessibility
> Versão do Assembly: 4.0.0.0
> Versão do Win32: 4.8.3752.0 built by: NET48REL1
> Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ## Geckofx-Winforms
> Versão do Assembly: 60.0.26.0
> Versão do Win32: 60.0.26.0
> Base de Código: file:///D:/CAIO%20ROCHA/Ferramentas/CSGO/Release-windows-1.1.3.3/Geckofx-Winforms.DLL
> ************** Depuração JIT **************
> Para habilitar a depuração just-in-time (JIT), o arquivo .config deste
> aplicativo ou computador (machine.config) deve ter o valor
> jitDebugging definido na seção system.windows.forms.
> O aplicativo também deve ser compilado com a depuração
> habilitada.
> 
> Por exemplo:
> 
> Quando a depuração JIT está habilitada, qualquer exceção sem tratamento
> será enviada ao depurador JIT registrado no computador,
> em vez de ser tratada nesta caixa de diálogo.


This error appeared after adding a sub id? If yes, then just click on "Counter-Strike: Global Offensive (329385)" again, then a window will open, you don’t change anything, just click "ok" and everything, the problem is solved;)


The game "Counter-Strike: Global Offensive" has a sub id "303386", please change;)

**Comment by despa1r1337** [comment]
[how to fix this error](https://imgur.com/wlZrAYy)

**Comment by EarsKilla** [comment]
also can be fixed with just restarting app after adding sub ids. this is very old bug. but it's bug :c

**Comment by caiovrcombat** [comment]
Thanks, guys!

Another question: How i can fix it?

http://prntscr.com/ofwmdp

**Comment by despa1r1337** [comment]
> Thanks, guys!
> 
> Another question: How i can fix it?
> 
> http://prntscr.com/ofwmdp

Valve banned all domains that were free, you can buy a domain here: https://www.reg.ru/ and use it by setting the domain according to: https://github.com/EarsKilla/Steam-Account-Generator/wiki/using-custom-mail-domain

**Comment by Ashesh3** [comment]
@caiovrcombat Just empty out the email field and it should work for now, without any need for custom domain (make the email input box empty, enable random email)

**Comment by despa1r1337** [comment]
> @caiovrcombat Just empty out the email field and it should work for now, without any need for custom domain (make the email input box empty, enable random email)

Today it was corrected by Valve. You must use purchased domains again.

**Comment by EarsKilla** [comment]
Please, retry with [dev 2.1.0](https://github.com/steam-account-creator/Steam-Account-Generator/releases/tag/v2.1.0)

it will be fixed now
