### ISSUE TITLE
Run program

### ISSUE THREAD

**Issue by wiktor000** [steam-account-creator/Steam-Account-Generator#29]
Hello,
Can you explain how to run this file/program ?

**Comment by despa1r1337** [comment]
> Hello,
> Can you explain how to run this file/program ?

1)  go to  https://github.com/steam-account-creator/Steam-Account-Generator/releases
last version: v1.1.3.3

2) click on: [https://github.com/steam-account-creator/Steam-Account-Generator/releases/download/v1.1.3.3/Release-windows-1.1.3.3.zip](url)

3) after downloading the zip file, extract it (I think you know how)

4)  
open the folder you extracted, it will have the name "Release-windows-1.1.3.3", and then open "SteamAccCreator.exe", ready

**Comment by despa1r1337** [comment]
if you have solved your problem, you can close the issue

**Comment by EarsKilla** [comment]
Also you need **windows** with installed .net framework and visual c++ redists (look [here](https://github.com/steam-account-creator/Steam-Account-Generator#requirements) for requirements)
