### ISSUE TITLE
one function not working

### ISSUE THREAD

**Issue by wiktor000** [steam-account-creator/Steam-Account-Generator#32]
Add free game to account not working

**Comment by despa1r1337** [comment]
> Add free game to account not working

Hello, could you describe your problem in more detail?
1. What game you do not add to your account?
2. Did you use instructions for adding games?  if you have not used the instruction, you can read [it here.](https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Find-sub-ID)

**Comment by wiktor000** [comment]
i want add counter strike global offensive with id 730, and when i login to created account i dont have this game
