### ISSUE TITLE
getting captcha loop with proxy ?

### ISSUE THREAD

**Issue by Marcofurio30** [steam-account-creator/Steam-Account-Generator#33]
Hello, what proxy should i use ? I've tried a lot of proxies but with all of them i'm getting captcha loop and the account are not created :(

Thank you for your help

**Comment by rufat845** [comment]
Captcha solving: Error: Getting captcha GID error!

**Comment by despa1r1337** [comment]
> Hello, what proxy should i use ? I've tried a lot of proxies but with all of them i'm getting captcha loop and the account are not created :(
> 
> Thank you for your help

It will work with http/https/socks4/socks5

**Comment by EarsKilla** [comment]
it will formatted like this: `socks4://127.0.0.1:5050/` so app will know how use proxy

**Comment by despa1r1337** [comment]
@Marcofurio30  if you have solved your problem, you can close the issue

**Comment by Marcofurio30** [comment]
Hello, sorry for the delay, its not about the format, the format is good, its about where you get proxies that works with steam. Because i've tried a lot of proxies but i always get that when i try to create account:
Recognizing captcha...
Then i solve the captcha
Creating account...
And then back to Recognizing captcha...

**Comment by EarsKilla** [comment]
Steam can probably detect proxies. Also [steam can ban IP](https://github.com/steam-account-creator/Steam-Account-Generator/wiki/F.A.Q.#ip-disallowed-or-banned--endless-captcha)
