### ISSUE TITLE
[Questions] Catch All Email

### ISSUE THREAD

**Issue by RetiredQQ** [steam-account-creator/Steam-Account-Generator#34]
Hi, can you implement catch all email?

**Comment by Ashesh3** [comment]
Need to elaborate more. What exactly do you want to achieve.

**Comment by RetiredQQ** [comment]
I want to use my own email. Can you implement that?

**Comment by despa1r1337** [comment]
> I want to use my own email. Can you implement that?

https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail

**Comment by EarsKilla** [comment]
seems solved. closing
