### ISSUE TITLE
Generator not working anymore

### ISSUE THREAD

**Issue by sk3nn1x** [steam-account-creator/Steam-Account-Generator#37]
The Captcha by the generator is not working anymore not even on Hand Mode

**Comment by EarsKilla** [comment]
related to #33 / #38  ?

**Comment by EarsKilla** [comment]
Please, retry with [dev 2.1.0](https://github.com/steam-account-creator/Steam-Account-Generator/releases/tag/v2.1.0)

ps, for long time no any reply i should close it
