### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by thomas0aotian** [steam-account-creator/Steam-Account-Generator#39]
Using the newest stable version1.1.3
autocaptcha by 2captcha
Captcha appears for one account more than one time
status went blank 
![image](https://user-images.githubusercontent.com/41808115/63218887-d5b17c80-c11a-11e9-908f-b0158d115b86.png)
![image](https://user-images.githubusercontent.com/41808115/63218890-e104a800-c11a-11e9-8173-4938326f01ab.png)
proxie not working 
![image](https://user-images.githubusercontent.com/41808115/63218892-ed890080-c11a-11e9-9d79-d1e66e871bf2.png)

either blank or recognizing captcha

**Comment by despa1r1337** [comment]
> Using the newest stable version1.1.3
> autocaptcha by 2captcha
> Captcha appears for one account more than one time
> status went blank
> ![image](https://user-images.githubusercontent.com/41808115/63218887-d5b17c80-c11a-11e9-908f-b0158d115b86.png)
> ![image](https://user-images.githubusercontent.com/41808115/63218890-e104a800-c11a-11e9-8173-4938326f01ab.png)
> proxie not working
> ![image](https://user-images.githubusercontent.com/41808115/63218892-ed890080-c11a-11e9-9d79-d1e66e871bf2.png)
> 
> either blank or recognizing captcha

bug :C

**Comment by EarsKilla** [comment]
related to #25
