### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by Pr0One** [steam-account-creator/Steam-Account-Generator#41]
Always doing: "Getting captcha..."
How to fix it?

**Comment by despa1r1337** [comment]
> Always doing: "Getting captcha..."
> How to fix it?

which version are you using?

**Comment by ShibaeO** [comment]
Hey,

My version is 2.0.1 pre realese i tried with and without Proxi, i from France i used french Proxi, use custom email (nboxkitten.com) and i stuck in : getting capcha

**Comment by EarsKilla** [comment]
seems like #27
