### ISSUE TITLE
how to avoid steam ip bans

### ISSUE THREAD

**Issue by p1nngu** [steam-account-creator/Steam-Account-Generator#42]
Hi some friends tried to make a bulk of accounts and they got ip banned by steam :) . Can someone tell me pls how can avoid this ?

**Comment by despa1r1337** [comment]
> Hi some friends tried to make a bulk of accounts and they got ip banned by steam :) . Can someone tell me pls how can avoid this ?

wait 24 hours, or use a proxy
by despa1r❤

**Comment by p1nngu** [comment]
> > Hi some friends tried to make a bulk of accounts and they got ip banned by steam :) . Can someone tell me pls how can avoid this ?
> 
> wait 24 hours, or use a proxy
> by despa1r❤

Yea i tried with proxy but still getting banned :)  why ?

**Comment by despa1r1337** [comment]
> Yea i tried with proxy but still getting banned :) why ?

at the moment, the program is not friendly with proxy, I also get a temporary ban after creating 11 accounts, but I wait ≈12-24 hours, after which I re-create 11 accounts and again get a temporary ban. And so in a circle;)

**Comment by p1nngu** [comment]
> > Yea i tried with proxy but still getting banned :) why ?
> 
> at the moment, the program is not friendly with proxy, I also get a temporary ban after creating 11 accounts, but I wait ≈12-24 hours, after which I re-create 11 accounts and again get a temporary ban. And so in a circle;)

ehh :) this takes too long to create 1000+ accs :/
