### ISSUE TITLE
im having an error in the steam account generator

### ISSUE THREAD

**Issue by shortguy123** [steam-account-creator/Steam-Account-Generator#43]
it says please enter a valid mail adress after solving captcha and sometimes it keeps on giving the captchas again and again even tho the account is not generated

**Comment by despa1r1337** [comment]
> it says please enter a valid mail adress after solving captcha and sometimes it keeps on giving the captchas again and again even tho the account is not generated

creator lazy ass and doesn't want to fix it ❤

**Comment by EarsKilla** [comment]
btw seems like #27

**Comment by despa1r1337** [comment]
i like earkilla tits❤

**Comment by shortguy123** [comment]
@EarsKilla  now what do i do? i need steam acounts badly can u reccomend something 4 me?

**Comment by EarsKilla** [comment]
don't know any working app at this moment.
also if your mail column looks like `steamlogin@` - you need to use paid domains.
but if it looks like this: `steamlogin@sample.domain` - here is all fine and problem can be with IP address or something else was broken 🤔

**Comment by despa1r1337** [comment]
> @EarsKilla now what do i do? i need steam acounts badly can u reccomend something 4 me?


do you have an mx record?
do you have your own paid domain?

**Comment by despa1r1337** [comment]
Close??

**Comment by EarsKilla** [comment]
think yeah, closing...
