### ISSUE TITLE
Gmail issue

### ISSUE THREAD

**Issue by RadicalRedemption** [steam-account-creator/Steam-Account-Generator#44]
The mail forward doesn't get verified automatically. I pressed "resend" a few times.

**Comment by despa1r1337** [comment]
> The mail forward doesn't get verified automatically. I pressed "resend" a few times.

[use instruction](https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail)

**Comment by EarsKilla** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
