### ISSUE TITLE
not give mail

### ISSUE THREAD

**Issue by YunusMoon** [steam-account-creator/Steam-Account-Generator#47]
Doesn't provide mail address and doesn't verify mail address. How do I fix it?
![mp](https://user-images.githubusercontent.com/55946327/65831245-39a19600-e2c0-11e9-80fc-9b3cbab7dde4.PNG)

**Comment by despa1r1337** [comment]
> Doesn't provide mail address and doesn't verify mail address. How do I fix it?
> ![mp](https://user-images.githubusercontent.com/55946327/65831245-39a19600-e2c0-11e9-80fc-9b3cbab7dde4.PNG)

you must use your purchase domain

**Comment by YunusMoon** [comment]
How add my domain?

**Comment by YunusMoon** [comment]
> > Doesn't provide mail address and doesn't verify mail address. How do I fix it?
> > ![mp](https://user-images.githubusercontent.com/55946327/65831245-39a19600-e2c0-11e9-80fc-9b3cbab7dde4.PNG)
> 
> you must use your purchase domain

How add my domain?

**Comment by EarsKilla** [comment]
https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-custom-mail-domain

**Comment by despa1r1337** [comment]
if your issue is resolved, you can close it.
