### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by cronex2011** [steam-account-creator/Steam-Account-Generator#53]
Hey guys, idk if this the right area for that, but who can explain me the modules for captcha solving. I know 2Captcha and Captchasolutions but can i add a new method for solving captchas with other modules ? 
thanks for your answer, hope anybody can help me :)

**Comment by EarsKilla** [comment]
Yes, you can add custom handles to solve captchas.
But I don't know any implemented module.

---

If you want implement your own module you need:
- Include [base library](https://github.com/steam-account-creator/ModuleBase) in your library  
- Add for your class interfaces that you want to implement  
  In your case you can add only `ISACHandlerReCaptcha` interface
- Add for your class attribute `SACModuleInfo` with fields `GUID`, `Module name`, `version`  
  **Note**: You can generate GUID in Visual Studio (idk about vs code). `Tools` > `Generate GUID`.  
  Or for example [here](https://www.guidgenerator.com/online-guid-generator.aspx)
- Implement it's methods

Also you can look at [sample module](https://github.com/steam-account-creator/SampleModule)/[ReCaptcha](https://github.com/steam-account-creator/SampleModule/blob/dev/SampleModule/ReCaptcha.cs).

Aaaand if i'm not wrong you can implement it only with .NET 4.7

**Comment by cronex2011** [comment]
okay thanks for you answer :D
my problem is, iam no a coder _P
I found sites like:
https://anti-captcha.com
https://azcaptcha.com
or 
https://www.drupal.org/project/captcha
its possible to implement it to your project ?
by the way, i love your project ;)

**Comment by EarsKilla** [comment]
You can use some services that work with API of Two/RuCaptcha or CaptchaSolutions.  

For example, you probably can use https://azcaptcha.com without any modules or modifying application.  
Just try to launch generator with option `-twoCaptchaDomain=https://azcaptcha.com`, select in `Captcha` tab solving via `2Captcha | RuCaptcha` and put your API key to `API Key` text input.

It's should work.

---

What's about `anti-captcha.com`... it's have different API and can be implemented through modules only (or by modifying generator but implement module seems easier than modify app).

**Comment by despa1r1337** [comment]
1) to start the generator with the option, you need to create the file "name.bat" in the folder with the program, after creating it, right-click and click "edit", type "SteamAccCreator.exe -twoCaptchaDomain = https: //azcaptcha.com"
2) save the "bat" file
3) Run the "bat" file.
4) go to the "Captcha" tab, insert your api key
5) create accounts;)

**Comment by cronex2011** [comment]
ahh okay thanks guys :)

**Comment by cronex2011** [comment]
yeah atm sure :)
