### ISSUE TITLE
Little Question

### ISSUE THREAD

**Issue by cronex2011** [steam-account-creator/Steam-Account-Generator#56]
short question, can someone tell me, with which site SAG the proxy checks?
would like to do this manually, because the program always crashes.
and do you have to re-verify the created steam accounts that are already verified in a certain amount of time? and if  SO ? like using your own domain.
Thanks

**Comment by despa1r1337** [comment]
@EarsKilla

**Comment by EarsKilla** [comment]
> short question, can someone tell me, with which site SAG the proxy checks?

https://github.com/steam-account-creator/Steam-Account-Generator/blob/3114d1049c96cc7225f535f5a558d8332b9808b6/SteamAccCreator/Web/Steam/SteamDefaultUrls.cs#L5
+
https://github.com/steam-account-creator/Steam-Account-Generator/blob/3114d1049c96cc7225f535f5a558d8332b9808b6/SteamAccCreator/Web/Steam/Join/SteamDefaultUrls.cs#L5

so it will be `https://store.steampowered.com/join/`
It's trying to get this link and verify content by this regex
https://github.com/steam-account-creator/Steam-Account-Generator/blob/3114d1049c96cc7225f535f5a558d8332b9808b6/SteamAccCreator/Web/ProxyManager.cs#L153

if you can configure your proxy checker to search for steam related strings (steam domains are fine) in returned content it will be good to exclude proxy that seems working but return shit like `failed to request page`

**Comment by cronex2011** [comment]
Okay the first question is solved amd the secend, wait :D
i mean, the generator verified the steam account and disabled the steam guard, okay. after few weeks, steam told me that i need to re verified the email adress, its only if i change the steam guard to on ? or is this not necessary if i disable the steam guard for ever ?
Understood ? :D

**Comment by EarsKilla** [comment]
I think I understand you now.
you're about green message on top of main steam window?
if so you can probably ignore this while steam guard don't enabled on account

**Comment by cronex2011** [comment]
yeah i mean this. its possible to re-verified this with his own domain too ?

**Comment by EarsKilla** [comment]
@Ashesh3

**Comment by cronex2011** [comment]
hey men, a new question :P
the programm created Accounts and all good but he dont disable the Steam guard :/
its possible to disable it with a code the steam send it to the email ? or can i manuell disable the steam guard ?
thanks

**Comment by despa1r1337** [comment]
close?

**Comment by despa1r1337** [comment]
closed
