### ISSUE TITLE
Gmail

### ISSUE THREAD

**Issue by xR3nd0X** [steam-account-creator/Steam-Account-Generator#57]
I pressed "resend" and reloaded the page, it did not work

**Comment by despa1r1337** [comment]
describe the problem in more detail, otherwise our samurai will not be able to help you❤. Regards, despa1r 😉

**Comment by msaad2110** [comment]
Can any one tell me how to add my custom domain from here? 
https://imgur.com/a/Bb4YxfY

I have already created a record in my DNS

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
