### ISSUE TITLE
Captcha Issue

### ISSUE THREAD

**Issue by msaad2110** [steam-account-creator/Steam-Account-Generator#59]
While using 2captcha I'm getting this error

https://imgur.com/a/WGMCdLh

**Comment by despa1r1337** [comment]
Email?

**Comment by despa1r1337** [comment]
Game for list?

**Comment by msaad2110** [comment]
No games for list and using my own domain for steam account.

**Comment by msaad2110** [comment]
Ah never mind the screen shot is incorrect while creating account I recieved incorrect captcha I don't know why

**Comment by EarsKilla** [comment]
you're using any proxy? it will be good if it's really private proxy

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.

**Comment by msaad2110** [comment]
> you're using any proxy? it will be good if it's really private proxy

Can you tell me where to find it? I tried multiple private proxies but still same error..

**Comment by EarsKilla** [comment]
> > you're using any proxy? it will be good if it's really private proxy
> 
> Can you tell me where to find it? I tried multiple private proxies but still same error..

sorry don't know because don't create to much accounts
