### ISSUE TITLE
Steam Guard turn off ?

### ISSUE THREAD

**Issue by cronex2011** [steam-account-creator/Steam-Account-Generator#60]
hey men, a new question :P
the programm created Accounts and all good but he dont disable the Steam guard :/
its possible to disable it with a code the steam send it to the email ? or can i manuell disable the steam guard ?
thanks

**Comment by despa1r1337** [comment]
hi, @cronex2011  wait for an answer from EarsKilla.

**Comment by EarsKilla** [comment]
at this moment haven't any solution to disable guard on accounts where it's enabled

**Comment by cronex2011** [comment]
hmm okay, thats sad :/ 60 accounts with handmode unuseable :P
