### ISSUE TITLE
Steam-Account-Generator 2.1.1

### ISSUE THREAD

**Issue by eizeize** [steam-account-creator/Steam-Account-Generator#61]
Is your software running?

**Comment by despa1r1337** [comment]
> Is your software running?

yes

**Comment by nefesim20** [comment]
Use custom domain. No any public domain available at this moment!

I have such a problem how do I tune ?

![7](https://user-images.githubusercontent.com/56896962/67516174-d7fafe80-f6a8-11e9-9963-4dd93982ebee.JPG)

**Comment by despa1r1337** [comment]
> Use custom domain. No any public domain available at this moment!
> 
> I have such a problem how do I tune ?
> 
> ![7](https://user-images.githubusercontent.com/56896962/67516174-d7fafe80-f6a8-11e9-9963-4dd93982ebee.JPG)

To fix this, you need to buy a domain, or use your mail.

[Instructions for setting up and using your mail](https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail)

**Comment by nefesim20** [comment]
google settings screen can not reach me can you reach me a link?

**Comment by nefesim20** [comment]
gmail account how do i add it where do i add it?

**Comment by despa1r1337** [comment]
email: yourmail@gmail.com

**Comment by nefesim20** [comment]
CREATED ACCOUNTS WANT STEAM PROTECTION HOW CAN I PREVENT THIS

**Comment by nefesim20** [comment]
![9](https://user-images.githubusercontent.com/56896962/67518708-f7e0f100-f6ad-11e9-8ad7-db030747ca8e.JPG)

**Comment by despa1r1337** [comment]
means that steam guard has not been disabled on your account

**Comment by nefesim20** [comment]
I create create no problem but can't get through the recaptcha screen

**Comment by nefesim20** [comment]
![12](https://user-images.githubusercontent.com/56896962/67520429-7be8a800-f6b1-11e9-9517-ccc6054fd1f9.JPG)

**Comment by despa1r1337** [comment]
choose what is required of you, click ok

**Comment by nefesim20** [comment]
I do this but it is not always verified and it repeats

**Comment by despa1r1337** [comment]
> I do this but it is not always verified and it repeats


do you use proxies? if not, close the program, open it and try again

**Comment by cronex2011** [comment]
hey men, i need help too and use this post for it, sry

who can explain to me why with a proxy the steam guard is not turned off, but with my real ip sure ?
and who can give me a good proxy list, and pls need it for free
thanks

**Comment by EarsKilla** [comment]
@eizeize
> I do this but it is not always verified and it repeats  
Google captcha say something like `error try again`?
If so it's okay especially when you using tor proxy.

---

@cronex2011
> who can explain to me why with a proxy the steam guard is not turned off, but with my real ip sure ?
valve eating sh... sometimes...  
if without stupid jokes... idk why, but sometimes it's getting you logged out by valve 🤔  

> proxy list, and pls need it for free  
try to take proxies from enhancement request #36

**Comment by cronex2011** [comment]
okay thanks men :)

**Comment by despa1r1337** [comment]
close?

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
