### ISSUE TITLE
how to NOT disable stem guard?

### ISSUE THREAD

**Issue by 9alexyt5** [steam-account-creator/Steam-Account-Generator#63]
I need quick aswer

**Comment by EarsKilla** [comment]
you need to start `v2.1.1` with launch option `-skipSteamGuard` or `-skipGuard` (no matter which one of option because it's like alias)

https://github.com/steam-account-creator/Steam-Account-Generator/blob/3114d1049c96cc7225f535f5a558d8332b9808b6/SteamAccCreator/Program.cs#L121

**Comment by 9alexyt5** [comment]
ty for reply! I am going to check that.

**Comment by EarsKilla** [comment]
Why you need to compile this?  
Just create file `noGuard.bat` (name don't matter and you can name it as you want) with content:
```bat
start SteamAccCreator.exe -skipSteamGuard
```

You should place this file in same directory with `SteamAccCreator.exe`

---

When file is created, you can run it with double click and it will skip steam guard disabling on account creation

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.

**Comment by 9alexyt5** [comment]
ok sorry i forgot about that i tried it and it gives like 21 isues and 3 warnings ;/

**Comment by EarsKilla** [comment]
how you download this?
`git clone -b dev --recursive-submodules https://github.com/steam-account-creator/Steam-Account-Generator.git` will works fine 🤔

**Comment by 9alexyt5** [comment]
where i need to paste it?

**Comment by EarsKilla** [comment]
> where i need to paste it?

In command line (you need git installed)? 🤔 
Or try to use [GitExtensions](https://github.com/gitextensions/gitextensions/releases/latest) to clone source code instead downloading as zip

btw, still don't understand why you need to compile this? it's already done in latest dev release.  
You need just run application with specified flag about i talk before.
