### ISSUE TITLE
Software crash when there are more than 5 threads

### ISSUE THREAD

**Issue by AmonKing** [steam-account-creator/Steam-Account-Generator#64]
Only 5 accounts can be created at the same time, and if more, it will crash.

**Comment by despa1r1337** [comment]
> Only 5 accounts can be created at the same time, and if more, it will crash.


do you use proxy?

**Comment by AmonKing** [comment]
No, I don't use it.

**Comment by AmonKing** [comment]
Another problem is that the success rate is much lower than before.
https://ftp.bmp.ovh/imgs/2019/10/1a87516635034d6c.png

**Comment by despa1r1337** [comment]
I also have this happens, but recently I used version 1.1.3.3 and it works

you can download it here https://github.com/steam-account-creator/Steam-Account-Generator/releases

**Comment by AmonKing** [comment]
Yeah, I already tried.
1.1.3.3 Cannot be disabledSteam Guard

**Comment by despa1r1337** [comment]
![image](https://user-images.githubusercontent.com/48297813/67961655-09c21700-fc0d-11e9-9ee2-9698ff83cdb2.png)
![image](https://user-images.githubusercontent.com/48297813/67961672-10508e80-fc0d-11e9-84c8-511eb80b0bfc.png)

**Comment by EarsKilla** [comment]
1.1.3.3 still using old way to disable guard

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
