### ISSUE TITLE
Failed to execute account creation

### ISSUE THREAD

**Issue by HuskyDotExe** [steam-account-creator/Steam-Account-Generator#66]
I'm getting this error everytime I try to create an account. It verifies email... does everything..reaches the disabling steam guard step and finally shows this

(15) Failed to execute account creation

![image](https://user-images.githubusercontent.com/57813722/68973598-ba870380-0814-11ea-91ab-6f769e8b9416.png)

**Comment by despa1r1337** [comment]
which version are you using?

**Comment by HuskyDotExe** [comment]
2.1.1

**Comment by despa1r1337** [comment]
when setting up mail, did you use this [instruction?](https://github.com/nullworks/accgen-web/wiki/Using-Your-Gmail-address-with-Steam-Account-Generator)

**Comment by HuskyDotExe** [comment]
I used the afraid method

**Comment by despa1r1337** [comment]
?

**Comment by despa1r1337** [comment]
> when setting up mail, did you use this [instruction?](https://github.com/nullworks/accgen-web/wiki/Using-Your-Gmail-address-with-Steam-Account-Generator)

if you have not used it, then try. Perhaps this is the solution.

**Comment by HuskyDotExe** [comment]
> ?

![image](https://user-images.githubusercontent.com/57813722/68976195-469c2980-081b-11ea-9bd9-7f413f516831.png)

https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Custom-mail-domain-with-afraid

This was what I'm referring to

**Comment by HuskyDotExe** [comment]
I'll try the gmail forward then

**Comment by despa1r1337** [comment]
> https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Custom-mail-domain-with-afraid
> 
> This was what I'm referring to

it hasn't worked for a long time :(

**Comment by HuskyDotExe** [comment]
Hi, I did the gmail setup and all and then tried creating an account again, but it gets stuck on verifying email part. I switched to 1.1.3.3 since I read it's the stable build.

Here's the log:

**Comment by olesiek** [comment]
It's problem with creator i think, last week everything worked perfectly, today it's getting error (15) Failed to execute account creation. Without any config changes.

**Comment by CripTonics** [comment]
I'm having problems same way

**Comment by olesiek** [comment]
Propably steam not sending mails on private domains. I installed mail server for 3 different domains and no one got email, tried on gmail and I got the email.

**Comment by HuskyDotExe** [comment]
Well I got the mail too, but I shouldn't be verifying it manually.. also if we do verify it manually we cant use the same mail twice to create accounts. (I guess we are not supposed to create a n number of emails for n number of accounts manually)

**Comment by olesiek** [comment]
> (I don't think we are supposed to create n number of emails for n number of accounts manually)

Yes u can make multiple account on the same email.

**Comment by HuskyDotExe** [comment]
Are you verifying mails manually while creating the account(s)?

**Comment by despa1r1337** [comment]
Hey.

As I personally noticed, something is wrong with the program.

deal with the error `Failed to execute account creation`

No matter how I tried, I didn’t get such an error at the time of the tests (I don’t know what it is connected with, I can’t help in any way: c)

`Now about the mails`:

1) does not confirm mail on the `purchased domain`. No matter how I try, I still get the message `No Email Received.. Try again!`
(1 screenshot)
![1 screenshot](https://user-images.githubusercontent.com/48297813/69000726-423c4300-08e5-11ea-8be7-627dd7ebb6f3.PNG)


Repeating the same procedure in another program, I see that the mail was confirmed, the account was created (2 screenshot)
![2  screenshot](https://user-images.githubusercontent.com/48297813/69000711-0ef9b400-08e5-11ea-9c0f-9a36409d20dc.PNG)


2)  `Gmail.com`

After setting up mail, the process of creating an account starts, it comes to confirming mail, mail is confirmed, but the program just hangs on the  `checking steam login`, and nothing more.

3) I wrote to the developer of the program, we are waiting for an answer.

If you can’t wait to create accounts, I can offer one option, use the [site](https://accgen.cathook.club)

**Comment by EarsKilla** [comment]
seems fixed. it's was mail handler server-side fault that now is fixed by @Ashesh3 (or/and it's team). now it will should work like before (with weird bugs, etc...)

**Comment by despa1r1337** [comment]
FIXED

**Comment by HuskyDotExe** [comment]
Yup, fixed
