### ISSUE TITLE
Always wrong Captcha

### ISSUE THREAD

**Issue by Bison4691** [steam-account-creator/Steam-Account-Generator#67]
Hello,

unfortunately it always says wrong Captcha. Doesnt matter which service I use or if I do it by hand

**Comment by ypc123** [comment]
The program doesn't work, I'm just laughing at your topic

also Captcha is not always wrong, Do not open troll topics!

**Comment by Bison4691** [comment]
What do you mean it doesnt work?

**Comment by ypc123** [comment]
Steam Account Generator is not running.

Mail system has a problem, Captcha running and no problem

**Comment by despa1r1337** [comment]
> Hello,
> 
> unfortunately it always says wrong Captcha. Doesnt matter which service I use or if I do it by hand

Hey. Unfortunately, the program does not work at the moment. But there is a way, you can use this [site](https://accgen.cathook.club/)

**Comment by EarsKilla** [comment]
working now?

**Comment by despa1r1337** [comment]
@ypc123 
@Bison4691 

Status: FIXED

**Comment by ypc123** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10389186/69372328-90b95b00-0cb2-11ea-9a48-3454513fe3f7.png)

but there is another problem?

**Comment by despa1r1337** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/10389186/69372451-c9f1cb00-0cb2-11ea-948f-513a83f80782.png)
> 
> but there is another problem?

cannot help in any way, for we ourselves do not know why this arises. Try using version: v1.1.3.3

**Comment by ypc123** [comment]
@despa1r1337 I couldn't run the old version as well

**Comment by despa1r1337** [comment]
> @despa1r1337 I couldn't run the old version as well

why?
