### ISSUE TITLE
NEW BUG Steam Guard Disabling Fail

### ISSUE THREAD

**Issue by cronex2011** [steam-account-creator/Steam-Account-Generator#69]
Hey boys, new Issue.
if i want to create account again, the generator told me that problem:
![11111](https://user-images.githubusercontent.com/29853461/70177830-68325780-16db-11ea-984e-259e738c600e.jpg)

settings are not changed, at domain settings the same and @domain.xyz 

pls help

**Comment by despa1r1337** [comment]
we know about this problem, nothing at the moment can not help. Use version 1.1.3.3, there is no such thing :)

**Comment by cronex2011** [comment]
okay but with this Version : 1.1.3.3 the generator dont disabled the steam guard !
whats the soloution for this ?

**Comment by cronex2011** [comment]
and i cant use my custom domain on your website : https://email.cathook.club

**Comment by despa1r1337** [comment]
> and i cant use my custom domain on your website : https://email.cathook.club
> 
> error: Domain is not configured correctly. Check navbar for a guide.

the site does not belong to us, did you use the instruction indicated on the site?

**Comment by despa1r1337** [comment]
> okay but with this Version : 1.1.3.3 the generator dont disabled the steam guard !
> whats the soloution for this ?

when creating an account, version 1.1.3.3 disables steam guard

**Comment by IT5Y** [comment]
> > 好的，但是使用此版本：1.1.3.3发电机不会禁用蒸汽防护罩！
> > 这有什么解决方案？
> 
> 创建帐户时，版本1.1.3.3禁用蒸汽防护

1.1.3.3Enable Proxy doesn't work

**Comment by despa1r1337** [comment]
> > > 好的，但是使用此版本：1.1.3.3发电机不会禁用蒸汽防护罩！
> > > 这有什么解决方案？
> > 
> > 
> > 创建帐户时，版本1.1.3.3禁用蒸汽防护
> 
> 1.1.3.3Enable Proxy doesn't work

the program is not friendly with proxies

**Comment by cronex2011** [comment]
> > okay but with this Version : 1.1.3.3 the generator dont disabled the steam guard !
> > whats the soloution for this ?
> 
> when creating an account, version 1.1.3.3 disables steam guard

no sir, i use 1.1.3.3 and they dont diabaled steam guard, only the programm"status" is = finished, no more
and the instruction are the same that i found here for custom domain. i dont change anything.
and why is the 2.1.1 broken ? you fix it or your partner ?

**Comment by EarsKilla** [comment]
@cronex2011 try 2.1.1 with launch option `-mailBoxChecks=15` (you can increase this value) and look what's happen. May be steam slowly delivering mails. idk...

**Comment by cronex2011** [comment]
@EarsKilla hey men ,i testet it with =60 but nothing. idk why 
i think its broken

**Comment by cronex2011** [comment]
@EarsKilla and now the programm is stopped at trying to verify email ...
in the 1.1.3.3 version i can create it easy but without to disable steam guard and i need it off :/
i cant change it off bc custom domain

**Comment by despa1r1337** [comment]
@EarsKilla

**Comment by EarsKilla** [comment]
@cronex2011 there is some known trouble with guard. it's seems that it's just randomly going to be enabled. even if you enable and disable. at this moment i have no idea how to make it working properly
