### ISSUE TITLE
Microsoft .NET Framework error

### ISSUE THREAD

**Issue by kafuuchino-s** [steam-account-creator/Steam-Account-Generator#70]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SteamAccCreator.Web.Mail.MailHandler.GetMails(MailBoxResponse response)
   在 SteamAccCreator.Web.Account.<GetGuardLinkFromMail>b__61_0()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 SteamAccCreator.Web.Account.<GetGuardLinkFromMail>d__61.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 SteamAccCreator.Web.Account.<DisableSteamGuard>d__57.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 SteamAccCreator.Web.Account.<Register>d__51.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 SteamAccCreator.Gui.MainForm.<BtnCreateAccount_Click>d__20.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4018.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SteamAccCreator
    程序集版本:2.1.1.0
    Win32 版本:2.1.1
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/SteamAccCreator.exe
----------------------------------------
NLog
    程序集版本:4.0.0.0
    Win32 版本:4.6.7.10445
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/NLog.DLL
----------------------------------------
Geckofx-Core
    程序集版本:60.0.39.0
    Win32 版本:60.0.39.0
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/Geckofx-Core.DLL
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4001.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
SACModuleBase
    程序集版本:1.0.0.0
    Win32 版本:1.0
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/SACModuleBase.DLL
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4001.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4018.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    程序集版本:4.0.0.0
    Win32 版本:4.8.3825.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.8.3825.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
RestSharp
    程序集版本:106.6.10.0
    Win32 版本:106.6.10.0
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/RestSharp.DLL
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.2.23222
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/Newtonsoft.Json.DLL
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.8.4001.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
HtmlAgilityPack
    程序集版本:1.11.14.0
    Win32 版本:1.11.14
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/HtmlAgilityPack.DLL
----------------------------------------
Geckofx-Winforms
    程序集版本:60.0.39.0
    Win32 版本:60.0.39.0
    基本代码:file:///C:/Users/kafuuchino/Downloads/DEV-windows-2.1.1/Geckofx-Winforms.DLL
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

![image](https://user-images.githubusercontent.com/51790568/70813601-b397e480-1e04-11ea-8fe6-9f131a6ad25c.png)

**Comment by despa1r1337** [comment]
did you install: [.NET Framework 4.7.2](https://dotnet.microsoft.com/download/dotnet-framework/net472) and [Visual C ++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)?

**Comment by kafuuchino-s** [comment]
i install .NET Framework 4.7.2,and Visual C ++ Redistributable for Visual Studio 2015

![image](https://user-images.githubusercontent.com/51790568/70843965-538d5680-1e75-11ea-8a9a-ebcde32e4871.png)

**Comment by despa1r1337** [comment]
> i install .NET Framework 4.7.2,and Visual C ++ Redistributable for Visual Studio 2015
> 
> ![image](https://user-images.githubusercontent.com/51790568/70843965-538d5680-1e75-11ea-8a9a-ebcde32e4871.png)
> ![image](https://user-images.githubusercontent.com/51790568/70843967-67d15380-1e75-11ea-9992-4a469bd4f015.png)

Do you get this error when you try to run a program?

**Comment by kafuuchino-s** [comment]
no，i get this error when the program disabling steam guard
![image](https://user-images.githubusercontent.com/51790568/70846744-45503200-1e97-11ea-9b45-2f8bb0230e3d.png)
![image](https://user-images.githubusercontent.com/51790568/70846754-59942f00-1e97-11ea-9a8b-5903f46b5be4.png)

**Comment by despa1r1337** [comment]
https://github.com/steam-account-creator/Steam-Account-Generator/releases/tag/v1.1.3.3 try this version

**Comment by kafuuchino-s** [comment]
v1.1.3.3 is ok ，thanks！

**Comment by despa1r1337** [comment]
> v1.1.3.3 is ok ，thanks！

if your problem is resolved, you can close this appeal. If you have any questions / problems, feel free to ask them. ;)
