### ISSUE TITLE
Proxies not working..

### ISSUE THREAD

**Issue by epicgamer11svg** [steam-account-creator/Steam-Account-Generator#71]
Whenever i use proxies it says the proxy is  bad and the captcha keeps  going on forever even after you do it (only  when using proxy) how do yo fix this and where can you get   good  proxies which  will work for this?

**Comment by despa1r1337** [comment]
> Whenever i use proxies it says the proxy is bad and the captcha keeps going on forever even after you do it (only when using proxy) how do yo fix this and where can you get good proxies which will work for this?

hi, the program is not friendly with proxies, it is better not to use them

**Comment by epicgamer11svg** [comment]
so will it work if we use a vpn?? like the your ip probably banned by steam issue?

**Comment by epicgamer11svg** [comment]
even with vpn on not proxy the captcha keeps looping and going on forever(with vpn on)

**Comment by despa1r1337** [comment]
> so will it work if we use a vpn?? like the your ip probably banned by steam issue?

try rebooting the router (in other words, the Internet)

**Comment by epicgamer11svg** [comment]
ok i will try and let you know. Thank you!
