### ISSUE TITLE
HELP ME PLEASE!!!

### ISSUE THREAD

**Issue by omni-1** [steam-account-creator/Steam-Account-Generator#73]
![image](https://user-images.githubusercontent.com/54331274/72205453-71a1a300-3483-11ea-9bf9-29fa7fa4e5da.png)
PLEASE HELP ME!!! SOLUTION :'((((((( i used a 2captcha key.... but it says that help!!!

**Comment by despa1r1337** [comment]
> ![image](https://user-images.githubusercontent.com/54331274/72205453-71a1a300-3483-11ea-9bf9-29fa7fa4e5da.png)
> PLEASE HELP ME!!! SOLUTION :'((((((( i used a 2captcha key.... but it says that help!!!

your balance is empty, top up your balance and try again

**Comment by omni-1** [comment]
OH LMFAOOOOO, thanks

**Comment by Roki100** [comment]
how did u use that mail domain? it shows its blacklisted for me

**Comment by despa1r1337** [comment]
> how did u use that mail domain? it shows its blacklisted for me

if he didn’t have a problem with the captcha balance, then during the mail confirmation, he would say that the domain is blocked

**Comment by despa1r1337** [comment]
it seems the problem is solved, can I close it? @omni-1
