### ISSUE TITLE
Crashing while checking proxies

### ISSUE THREAD

**Issue by EinWildesPanda** [steam-account-creator/Steam-Account-Generator#81]
I'm using the newest version (2.1.1). And as the title describes: The generator crashes while trying to check proxies. Errorlog: https://paste.squarecode.de/3S79QzDNNJ
I don't know if anything's missing, if something's missing, hmu

**Comment by despa1r1337** [comment]
> I'm using the newest version (2.1.1). And as the title describes: The generator crashes while trying to check proxies. Errorlog: https://paste.squarecode.de/3S79QzDNNJ
> I don't know if anything's missing, if something's missing, hmu


the program is not friendly with the proxy. it’s better not to use them.

**Comment by EinWildesPanda** [comment]
well, that's bad 'cause I need quite a few accounts. Do you know after how many tries steam bans your ip for how long?

**Comment by EinWildesPanda** [comment]
The weird thing is that the first check of a batch of proxies actually worked, but now it doesn't

**Comment by despa1r1337** [comment]
> well, that's bad 'cause I need quite a few accounts. Do you know after how many tries steam bans your ip for how long?

after 11 created accounts, your main ip is blocked
