### ISSUE TITLE
Domain banned after 15 account made

### ISSUE THREAD

**Issue by IdioteMan** [steam-account-creator/Steam-Account-Generator#82]
Yesterday i bough a domain set it up and started generating account and my domain got banned after 15 account created. Is that normal?

**Comment by despa1r1337** [comment]
site? tk? space? what does your domain end with?

**Comment by IdioteMan** [comment]
ionos and domain ending with .com

**Comment by IdioteMan** [comment]
And the account are suspended from connecting in steam.

**Comment by despa1r1337** [comment]
solved?
