### ISSUE TITLE
How to setup custom domain?

### ISSUE THREAD

**Issue by ShazadSkriptREPO** [steam-account-creator/Steam-Account-Generator#83]
need some help, i already add mx record to domain but idk how to setup it in application

**Comment by despa1r1337** [comment]
in the program: check the` random mail` , and then in the `Email` field : @`yourdomen``.com/ru/site`

**Comment by despa1r1337** [comment]
solved?

**Comment by encloinc** [comment]
does it have to be .com? I bought a ".org"
