### ISSUE TITLE
Can't get my email domain to work.

### ISSUE THREAD

**Issue by Bodhi-R** [steam-account-creator/Steam-Account-Generator#85]
![image](https://user-images.githubusercontent.com/48874598/78729406-4db80580-797d-11ea-9ed7-e4f9cd6f47a7.png)

**Comment by xGodThunder** [comment]
i am facing same issue.

**Comment by despa1r1337** [comment]
yeet696969696chickenkiller.com - is this your inbox?

**Comment by despa1r1337** [comment]
![image](https://user-images.githubusercontent.com/48297813/78783495-6390ef00-79ac-11ea-9f3c-d04394d5bb3e.png)
working

**Comment by ricardosxx** [comment]
> ![图片](https://user-images.githubusercontent.com/48297813/78783495-6390ef00-79ac-11ea-9f3c-d04394d5bb3e.png)
> 工作中

Can you help me to solve this problem? I have the same problem

**Comment by LD50-ASHES** [comment]
same here i need help with this as well

**Comment by despa1r1337** [comment]
https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail 

Enter `forward@mailhost.root.sx` for the email below in all cases

**Comment by ricardosxx** [comment]
> @Bodhi-R
> @LD50-ASHES
> @ricardosxx
> @xGodThunder
> 
> https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail
> 
> Enter `forward@mailhost.root.sx` for the email below in all cases


> @Bodhi-R
> @LD50-ASHES
> @ricardosxx
> @xGodThunder
> 
> https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail
> 
> Enter `forward@mailhost.root.sx` for the email below in all cases

Thank you for your help. I will try whether this method works for me

**Comment by xGodThunder** [comment]
@ricardosxx  hey buddy, it is now tutorial you shared.
I am using my custom domain email and it is not working, 
I am not pro, if you can help us by creating another tutorial like this for custom email that would be super awesome <3

**Comment by xGodThunder** [comment]
@ricardosxx i have used this : https://freedns.afraid.org/subdomain/, but still no luck.
it is complaining about "unable to contact inbox service" :(

**Comment by ricardosxx** [comment]
> @ricardosxx i have used this : https://freedns.afraid.org/subdomain/, but still no luck.
> it is complaining about "unable to contact inbox service" :(

me too:（

**Comment by despa1r1337** [comment]
> @ricardosxx i have used this : https://freedns.afraid.org/subdomain/, but still no luck.
> it is complaining about "unable to contact inbox service" :(

using ONLY GMAIL!!
https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail
Enter forward@mailhost.root.sx for the email below in all cases

**Comment by xGodThunder** [comment]
@despa1r1337  thanks for commenting.
I am trying forwarding to  t'native@mailhost.root.sx'  in Gmail but it is not getting verified.
I have tried "re-send" email many times and refresh but not happening.

Thank you for your precious time.

**Comment by xGodThunder** [comment]
@despa1r1337 
![error](https://user-images.githubusercontent.com/48578610/79681386-85556600-8237-11ea-8ef5-b2bbed5eb96b.PNG)
I made the forwarding set,
but when i use the steam creator app and provide "myemail@gmail.com" in email field, it again complains about "cannot communicate with inbox service".
and
in web app (the above image) when i write my credentials, it doesn't accept, it again popup  asking the same credentials :(

**Comment by despa1r1337** [comment]
> @despa1r1337 thanks for commenting.
> I am trying forwarding to t'[native@mailhost.root.sx](mailto:native@mailhost.root.sx)' in Gmail but it is not getting verified.
> I have tried "re-send" email many times and refresh but not happening.
> 
> Thank you for your precious time.



> native@mailhost.root.sx

you need to use` forward@mailhost.root.sx` instead of` native@mailhost.root.sx`

**Comment by xGodThunder** [comment]
@despa1r1337  lovely, it worked!
Just curious, if you provide quick steps to use gmail on steam-creator-electron-app,
what to fill in 

1. email:
2. login:
3. pass:

fields.

Thank you so much, you're great!

**Comment by despa1r1337** [comment]
@ricardosxx

**Comment by ItsOnlyMeNL** [comment]
I'm good thanks. I have compiled my own version of this to use my own servers for this :)

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
