### ISSUE TITLE
cant get emails working

### ISSUE THREAD

**Issue by LD50-ASHES** [steam-account-creator/Steam-Account-Generator#86]
i need anyone to show me how to fix this 
![image](https://user-images.githubusercontent.com/56386412/79253334-eddcc580-7e7a-11ea-8f05-93004ee5de59.png) 
i don't need an expert i just need help from someone who can help me

**Comment by despa1r1337** [comment]
https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail

Enter `forward@mailhost.root.sx` for the email below in all cases
