### ISSUE TITLE
How can i write socks4 proxy ?

### ISSUE THREAD

**Issue by ugurbyt** [steam-account-creator/Steam-Account-Generator#88]
Hello , thank you for software.
How can i write socks4 proxy.
I tried
socks4://
sock4://
socks://
sock://
but does not working.
How can i fixed ?

**Comment by despa1r1337** [comment]
> Hello , thank you for software.
> How can i write socks4 proxy.
> I tried
> socks4://
> sock4://
> socks://
> sock://
> but does not working.
> How can i fixed ?

the program is not friendly with the proxy. Do not use them.
