### ISSUE TITLE
Cannot Communicate with inbox service.

### ISSUE THREAD

**Issue by xglymps** [steam-account-creator/Steam-Account-Generator#90]
As you can see here:
![image](https://user-images.githubusercontent.com/54585842/84424637-4ed50f80-ac18-11ea-9f13-14f89ce3799e.png)
It does not let me create any accounts

**Comment by despa1r1337** [comment]
https://github.com/steam-account-creator/Steam-Account-Generator/issues/85

**Comment by despa1r1337** [comment]
@xglymps  solved?

**Comment by xglymps** [comment]
No :/
![image](https://user-images.githubusercontent.com/54585842/84690469-70950600-af3a-11ea-8e8e-61d41f80f5ea.png)

**Comment by despa1r1337** [comment]
> No :/
> ![image](https://user-images.githubusercontent.com/54585842/84690469-70950600-af3a-11ea-8e8e-61d41f80f5ea.png)

using ONLY GMAIL!!
https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail
Enter `forward@mailhost.root.sx` for the email below in all cases

**Comment by despa1r1337** [comment]
@xglymps

**Comment by ldapuser** [comment]
i have same error. Not working using gmail

**Comment by despa1r1337** [comment]
> i have same error. Not working using gmail

did you do what i told you? did you send letters to forward@mailhost.root.sx?

**Comment by ldapuser** [comment]
![image](https://user-images.githubusercontent.com/17813156/85041420-94528900-b192-11ea-8f46-6356bf6fdc15.png)

**Comment by despa1r1337** [comment]
@ldapuser  Have you read this topic? https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail

**Comment by ldapuser** [comment]
my bad, on the tab "forwarding and pop/imap" was disabled forwarding. Working now.
