### ISSUE TITLE
I dont want disable steam guard

### ISSUE THREAD

**Issue by gnodyoz** [steam-account-creator/Steam-Account-Generator#91]
i dont want it because i dont need and im getting error when i try to create acoount. if you add this option it can be good

**Comment by despa1r1337** [comment]
> i dont want it because i dont need and im getting error when i try to create acoount. if you add this option it can be good

what error do you get

**Comment by despa1r1337** [comment]
No any replay after 3 days. Gonna close issue. If any related questions, reopen issue.
