### ISSUE TITLE
Cannot comunicate with inbox service ! 

### ISSUE THREAD

**Issue by REKTER3333** [steam-account-creator/Steam-Account-Generator#92]
i cant create any account

**Comment by despa1r1337** [comment]
> i cant create any account

what mail do you use?

**Comment by 1nhale** [comment]
same issue with me.. it says cannot comunicate with inbox service

**Comment by despa1r1337** [comment]
> same issue with me.. it says cannot comunicate with inbox service

what mail do you use?
