### ISSUE TITLE
How to make it working

### ISSUE THREAD

**Issue by sonny2589** [steam-account-creator/Steam-Account-Generator#93]
I have dowloaded .zip file. Now someone please guide me how to make this steam account generator working.

**Comment by sonny2589** [comment]
I have dowloaded .zip file. Now someone please guide me how to make this steam account generator working. I have already used commend bot from this website github and I need steam accounts for my commend bot. Commend bot is already working. Now please someone guide me. I have downloaded this steam account generator. Now how to build this or from where to start this account generator?

**Comment by despa1r1337** [comment]
> I have dowloaded .zip file. Now someone please guide me how to make this steam account generator working. I have already used commend bot from this website github and I need steam accounts for my commend bot. Commend bot is already working. Now please someone guide me. I have downloaded this steam account generator. Now how to build this or from where to start this account generator?

[How to find sub ID](https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Find-sub-ID)

check the boxes: random login, random password, add for list, neat login, neat password.

In the email field, enter your mail (we recommend gmail)
read  topic https://github.com/steam-account-creator/Steam-Account-Generator/wiki/Using-gmail
note that instead of mailhost.root.sx you need to use `forward@mailhost.root.sx`

Go to the captcha tab and enter your key.


well, or you can use this site https://accgen.cathook.club/

**Comment by sonny2589** [comment]
What I m asking is when i downloaded in past like commend bot/report bot i have to build that bot in my pc and then i use them from Powershell window. I have downloaded this steam account generator.zip file now after extracting what should I do? Can I get your discord it will be helpfull for me. or I request you to write step here. Because there in no .bat or .exe file to run in extracted directory.

**Comment by despa1r1337** [comment]
did you download from here? https://github.com/steam-account-creator/Steam-Account-Generator/releases

**Comment by sonny2589** [comment]
Yes

**Comment by despa1r1337** [comment]
> Yes

:/
![image](https://user-images.githubusercontent.com/48297813/88578728-abb64900-d051-11ea-8156-e4be11a93d53.png)

**Comment by sonny2589** [comment]
I have downloaded this. Done this

> forward@mailhost.root.sx

this "forward@mailhost.root.sx" isn't working. Would you please give me your discord.

**Comment by despa1r1337** [comment]
> I have downloaded this. Done this
> 
> > [forward@mailhost.root.sx](mailto:forward@mailhost.root.sx)
> 
> this "[forward@mailhost.root.sx](mailto:forward@mailhost.root.sx)" isn't working. Would you please give me your discord.

screenshot of error?
